version: "3.7"
services:  
    # Spark Master
    spark:
        image: chethanuk/spark:3.0.1-kpy38
        user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        hostname: spark
        networks:
            - spark
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/:/usr/local/spark/
            - ./spark/resources:/usr/local/spark/resources
        ports:
            - "8181:8080"
            - "7077:7077"

    spark-worker-1:
        image: chethanuk/spark:3.0.1-kpy38
        user: root
        networks:
            - spark
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/:/usr/local/spark/
            - ./spark/resources:/usr/local/spark/resources

    spark-worker-2:
        image: chethanuk/spark:3.0.1-kpy38
        user: root
        networks:
            - spark
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/:/usr/local/spark/
            - ./spark/resources:/usr/local/spark/resources

    spark-worker-3:
        image: chethanuk/spark:3.0.1-kpy38
        user: root
        networks:
            - spark
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ./spark/:/usr/local/spark/
            - ./spark/resources:/usr/local/spark/resources

    #Jupyter notebook
    # spark-jupyter:
    #     image: jupyter/pyspark-notebook:latest
    #     user: root
    #     networks:
    #         - spark
    #     ports:
    #       - "8888:8888"
    #       - "4040-4080:4040-4080"
    #     volumes:
    #       - ./spark/:/home/jovyan/work/
    #     #   - ./spark/:/usr/local/spark/

networks:
    spark: